### ISSUE TITLE
Performing operations in background thread

### ISSUE THREAD

**Issue by SAGARSURI** [vrendina/RxQueue#1]
How to perform all the operations in the queue in background thread? I tried using subscribeOn() but still its getting executed in the main thread.

**Comment by vrendina** [comment]
For RxJava subjects in general, not just the QueueSubject, the `subscribeOn` operator has no effect on upstream operations. If you would like to execute a block of code on a different thread downstream from the events in the queue you should use the `observeOn` operator. 

I'd be happy to help you with your code if you want to post a snippet of what you are trying to do.

**Comment by vrendina** [comment]
This link might provide some more insight for you:

https://github.com/ReactiveX/RxJava/issues/2805

**Comment by SAGARSURI** [comment]
Thanks for the quick reply. Does QueueSubject maintain sequential execution ?

**Comment by vrendina** [comment]
You are welcome to look at the existing unit tests and source code and submit additional tests if there is a specific functionality you are trying to achieve and wish to test. 

As items are emitted from the subject your observer is going to receive them from the queue in the expected FIFO order. When you add items to the queue you call `onNext` on your subject, which calls `add` on the `ConcurrentLinkedQueue`, then if there is an observer it will drain the queue to that observer. 

Take a look at the source code and also take a look at `SerializedSubject` in RxJava if you are thinking about calling `onNext` from multiple threads.

**Comment by SAGARSURI** [comment]
Thanks for the reply. I achieved my requirements by using the `observeOn()`
